notifications:
  email: false

language: go

go:
  - "1.14"

sudo: false

services:
  - docker

install:
  - go mod download

env:
  - TARGET=test-unit
  - TARGET=build
  - TARGET=docker

script: make $TARGET
